all:
  hosts:
    lsxsrv:
      ansible_host: 192.168.0.56
      ansible_user: ls
      ansible_ssh_private_key_file: /home/leos/.ssh/id_lsxsrv
    hs:
      ansible_host: 192.168.0.56
      ansible_user: ls
      ansible_ssh_private_key_file: /home/leos/.ssh/id_lsxsrv
