- block:
    - name: Get K8S ip
      command: >-
        kubectl -n posthog get ingress -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}'
      register: K8S_IP

    - name: Create Caddyfile
      become: yes
      template:
        src: templates/Caddyfile
        dest: /etc/caddy/Caddyfile

    - name: Reload Caddy
      command: caddy reload --config /etc/caddy/Caddyfile

  become: no
