- name: Add Kubectl GPG apt Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key

- name: Add Kubectl Repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
    update_cache: true

- name: Install Kubectl
  apt:
    name:
      # Почему не учитывается зависимость от k8s (kube-apiserver)?
      # https://kubernetes.io/releases/version-skew-policy/#kubectl
      - kubectl=1.24.7-00
    state: present
    update_cache: true
    allow_downgrade: yes
