# Как избавиться от block? Зачем?
- block:
    - name: Create values file
      template:
        src: hs-values.yaml
        dest: hs-values.yaml
    # Стоит ли использовать command? Почему не FQCN?
    - name: Add humansignals to helm repo
      #command: "helm repo add posthog {{ hs_chart }} "
      kubernetes.core.helm_repository:
        name: humansignals
        repo_url: "{{ hs_chart }}"

#    - name: Update helm repo
#      command: "helm repo update"

    - name: Install humansignals
      kubernetes.core.helm: 
        chart_repo_url:  "{{ hs_chart }}"
        chart_ref: posthog
        values_files: hs-values.yaml
        create_namespace: yes    
        name: posthog
        release_namespace: posthog
        wait: True
        replace: True
        update_repo_cache: True        

    #  shell: "helm upgrade --install -f hs-values.yaml --timeout 30m --create-namespace --namespace posthog posthog posthog/posthog --wait --wait-for-jobs --debug"

    # Опять шелл. Избавься.
    - name: Patch configmap
      shell: >-
        kubectl -n ingress-nginx patch configmap ingress-nginx-controller -p '{"data":{"use-forwarded-headers": "true"}}'

  become: false
