---

  - name: Add Caddy GPG apt Key
    apt_key:
      url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
      state: present
    register: add_repository_key  

  - name: Add Caddy Repository
    apt_repository:
      repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
      state: present  
      filename: caddy
      update_cache: true

  - name: Install Caddy
    apt:
      name:
        - caddy
      state: latest
      update_cache: true