---
# tasks file for humansignals
#- include_tasks: default.yml
#- include_tasks: install_base.yml
#- include_tasks: install_docker.yml
#- include_tasks: install_caddy.yml
#- include_tasks: install_kubectl.yml
- include_tasks: install_minikube.yml
