# Придумай как избавиться от шелла
# Если ты используешь k8s_ver в других местах, то почему тут не используешь?
- name: start minikube from another shell
  ansible.builtin.systemd:
    name: minikube
    state: started
    enabled: yes
#  shell: su - {{ ansible_user }} -c "minikube start --addons=ingress --memory=max --cpus=max --kubernetes-version={{ k8s_ver }}"

# Как избавиться от ожидания?
# HINT: systemctl start *service name*
- name: Wait for 1 minute to start minikube services
  pause:
    minutes: 1
